### ISSUE TITLE
mutli-worlds composite script

### ISSUE THREAD

**Issue by cgmckeever** [nicolaschan/minecraft-backup#11]
@nicolaschan ... well, it almost works ... 

It appears that when I run the script below, I get the error of a file changing i the `world_nether` ... any thoughts how to track down how/why?  --- Really appreciate it

OUTPUT:
```
world
world_nether
tar: ./DIM-1/region/r.-1.0.mca: file changed as we read it
tar: .: file changed as we read it
world_the_end
```

```
#!/bin/bash

echo world
mkdir -p /root/backups/world
./backup.sh -c -i /usr/games/minecraft/world -o /root/backups/world

echo world_nether
mkdir -p /root/backups/world_nether
./backup.sh -c -i /usr/games/minecraft/world_nether -o /root/backups/world_nether

echo world_the_end
mkdir -p /root/backups/world_the_end
./backup.sh -c -i /usr/games/minecraft/world_the_end -o /root/backups/world_the_end

```

**Comment by nicolaschan** [comment]
Have you tried setting the screen/tmux session name (using the `-s` flag)?

The `file changed as we read it` error happens because the Minecraft server auto-saves the world causing it to change in disk. This interrupts tar and will likely result in a corrupted backup. To prevent this, the backup script sends `save-off` and `save-on` commands to the Minecraft server which temporarily disables and then re-enables autosaving.

**Comment by cgmckeever** [comment]
I have that set implicitly in the defaults .. I can try the `-s` to ensure it is catching

```
# Default Configuration
SCREEN_NAME="minecraft" # Name of the GNU Screen or tmux pane your Minecraft server is running in
SERVER_WORLD="" # Server world directory
BACKUP_DIRECTORY="" # Directory to save backups in
MAX_BACKUPS=128 # -1 indicates unlimited
DELETE_METHOD="thin" # Choices: thin, sequential, none; sequential: delete oldest; thin: keep last 24 hourly, last 30 daily, and monthly (use with 1 hr cron interval)
COMPRESSION_ALGORITHM="gzip" # Leave empty for no compression
COMPRESSION_FILE_EXTENSION=".gz" # Leave empty for no compression; Precede with a . (for example: ".gz")
COMPRESSION_LEVEL=3 # Passed to the compression algorithm
ENABLE_CHAT_MESSAGES=true # Tell players in Minecraft chat about backup status
PREFIX="Backup" # Shows in the chat message
DEBUG=false # Enable debug messages
SUPPRESS_WARNINGS=false # Suppress warnings
WINDOW_MANAGER="screen" # Choices: screen, tmux
```

**Comment by cgmckeever** [comment]
Same error 

```
#!/bin/bash

echo world
mkdir -p /root/backups/world
./backup.sh -c -i /usr/games/minecraft/world -o /root/backups/world -s minecraft

echo world_nether
mkdir -p /root/backups/world_nether
./backup.sh -c -i /usr/games/minecraft/world_nether -o /root/backups/world_nether -s minecraft
```

**Comment by cgmckeever** [comment]
Im going to try to manually turn the save off

**Comment by cgmckeever** [comment]
interesting running the command by itself seems to work,
Im going to add a SLEEP between them .. maybe when it is re-enabled, it starts saving and the next one tries to tar during a save

**Comment by nicolaschan** [comment]
Oh! Immediately after the backup script finishes the backup it does a `save-all` to make sure that any changes while saving was disabled are saved. The script may exit before the `save-all` finishes because it cannot easily detect when the `save-all` has finished. 

A quick hack to fix this would be to add a `sleep` between them. Perhaps we really do need the multiple worlds backup so that we can turn `save-off` for all of them and then once all of the backups are done then turn `save-on` again.

**Comment by cgmckeever** [comment]
sleep works .. that was it

**Comment by cgmckeever** [comment]
Thank you
